runelite/runelite.net

src/_data/hero.js, src/components/hero.js, src/components/navigation.js
- Add new button for macOS download
- Change max width of the Hero contents to 1000px from 800px (to fit new
button)
- Move stargazers button to top-right to navigation
Preview:
=> Add macOS download button

src/_data/features.js
I fixed various grammar/spelling errors and adjusted titles and descriptions to convey what the plugins do in a better way.
=> Adjust titles and descriptions of features

src/components/navigation.js
=> Add Patreon link

src/api.js, src/components/hero.js, src/containers/home.js, src/redux/modules/git.js, src/redux/modules/runelite.js, src/redux/reducer.js, src/redux/routes.js
This requires allowing CORS requests from https://runelite.net on RuneLite API side.
Preview:
=> Add session count to Hero

src/_posts/2018-03-22-1.3.1-Release.md
Thought this line could read a little more smoothly :)
=> Rewrite changes to the prayer flick plugin

.travis.yml, package-lock.json, package.json, src/index.js
When website is pre-rendered skip hydration part and directly re-render
entire website to prevent artifacts left behind from pre-rendered
index.html.
=> Don't hydrate website when pre-rendered

src/_posts/2018-05-03-1.3.7-Release.md
`git shortlog runelite-parent-1.3.7...runelite-parent-1.3.6 --no-merges`
The 2 auto-updater commits are trimmed out.
=> Add a more recent shortlog for the 1.3.7 changes

src/_posts/2018-04-12-1.3.4-Release.md
I used my first name when I wrote this update to match the other blog post authors, but that's practically anonymous since everybody knows me as "Soy" here.
=> Reauthor 1.3.4's blog post with a more familiar name

package-lock.json, package.json, src/components/hero.js
Thanks to NPM audit fix, this resolves over 100 vulnerabilities, one of
them critical.
=> Resolve NPM vulnerabilities

package-lock.json, package.json, src/blog.js, src/components/app.js, src/containers/blog-show.js, src/containers/blog.js, src/containers/home.js
This will code-split pages to chunks and so increase overall performance
of website while reducing the bundle size.
=> Add support for code-splitting

.travis.yml, README.md, package.json, rollup.config.js, src/blog.js, src/index.js
- Make prettier apply to more files
- Make prerendering crawl the website
- Reset /public/404.html after crawling as that one is important
=> More prerendering, cleanup

config-overrides.js, now.json, package-lock.json, package.json
For more informations: https://zeit.co/docs/integrations/now-for-github
Example PR with now.sh integration: https://github.com/deathbeam/runelite.net/pull/1
=> Prepare for now.sh support

.gitignore, src/_data/links.js, src/components/navigation.js
Preview: https://runelitenet-bomwawgiqb.now.sh/
=> Add Twitter link to homepage

.eslintrc, .prettierrc, config-overrides.js, package-lock.json, package.json, src/api.js, src/blog.js, src/components/app.js, src/components/async.js, src/components/commit.js, src/components/feature.js, src/components/footer.js, src/components/hero.js, src/components/layout.js, src/components/loader.js, src/components/meta.js, src/components/navigation.js, src/components/redirect.js, src/index.js, src/middleware/thunk-middleware.js, src/modules/runelite.js, src/parse-blog.js, src/parse-blog.test.js, src/routes/blog-show.js, src/routes/blog.js, src/routes/features.js, src/routes/home.js, src/routes/logged-in.js, src/routes/not-found.js, src/routes/xp-show.js
=> Remove standard.js, use provided eslint

src/components/hero.js
=> Use 32bit Windows download on 64bit systems

config-overrides.js, package-lock.json, package.json
=> Validate generated XML during build process

src/modules/runelite.js
=> Make XP tracker fetching run in parallel

src/modules/runelite.js
=> Sort XP tracker parallel entries by date

src/routes/xp-show.js
=> Fix start/end date xp tracker substraction

src/modules/runelite.js, src/routes/xp-show.js
=> Cleanup XP tracker code a bit

app.json, config-overrides.js, now.json
Example of PR deployement: https://github.com/deathbeam/runelite.net/pull/4 and the link to deployement itself: https://github.com/deathbeam/runelite.net/pull/4
=> Replace now.sh integration with Heroku

README.md, package.json, src/components/app.scss
Fixes:
- https://github.com/runelite/runelite.net/issues/127
- https://github.com/runelite/runelite/issues/6211
=> #127 Fixes build issues, fixes dropdown issues

src/routes/tag-show.js
Depends on/see: runelite/runelite#5972
=> Add support for displaying variation tags

src/_posts/2018-11-08-10-00-1.4.25-Release.md
These features are already mentioned in the same small improvements list.
=> Remove duplicated updates from 1.4.25 release post

src/modules/runelite.js
=> Disable examine info

src/components/_variables.scss, src/components/app.scss, src/routes/xp-show.css, src/routes/xp-show.js
=> Use SCSS variables for theming the website

src/modules/runelite.js
This reverts commit dea99b7bac69c90dab58eba5d58c4a13edb4348d.
=> Revert "Disable examine info"

src/modules/index.js, src/modules/item.js, src/modules/runelite.js, src/modules/xp.js, src/routes/tag-show.js, src/routes/xp-show.js
- Split Item module from RuneLite module
- Split Xp module from RuneLite module
=> Split RuneLite module to smaller modules

src/components/prepare.js, src/routes/gh-auth-code.js, src/routes/home.js, src/routes/tag-show.js, src/routes/tag.js, src/routes/xp-show.js
This allows for easier and more readable fetching of initial component
data in future.
=> Add prepare HOC and use it in routes

src/components/hero.js
=> Add support for Linux platform detection

src/_data/hero.js
=> Add button for Linux64 AppImage download and 1.6.2 launcher release downloads

src/_data/hero.js
=> Use fixed-width FontAwesome icons for downloads

README.md, src/blog.js
=> Add `skip: true` blog metadata that skips home page display

src/components/footer.js, src/util.js
=> Add RSS feed link to footer

src/blog.js, src/components/app.js, src/components/not-found.js, src/routes/blog-show.js
=> Handle missing blog posts correctly

src/blog.js, src/routes/blog.js
=> Make blog post URLs case insensitive

src/routes/account.js
=> Properly show selected account in /account/home

src/components/not-found.js
=> Fix not-found spelling and missing punctuation

src/modules/account.js
=> Focus OAuth tab after opening it

src/routes/account/home.js
This looks a lot more polished and brings important information to
front.
=> Improve slayer task display in account/home

src/routes/account/home.js
=> Add boss images to boss task display in account/home

src/routes/account/home.js
=> Fix Deranged Archaeologist boss icon

src/routes/account.js, src/routes/xp-show.js
=> Add NotFound handling to account/ and xp/show pages

package.json, public/404.html, public/index.html
=> Make npm run fix also reformat HTML

src/components/navigation.js
=> Add link to HTTP apidocs

src/components/navigation.css
=> add border to light navbar

src/components/hero.js
That flash is nasty :) You don't see it locally (you'd have to introduce artificial latency) but you do see it in production.
=> fix hero flash by preloading images before state update

config-overrides.js, redirect.html, redirect.js
This do not works yet, I just want to see if its redirecting when its deployed to Netlify
=> Add support for generating redirects

src/_posts/2019-08-29-10-00-1.5.32-Release.md
No screenshots for this one because nothing was really screenshottable.
=> Add 1.5.32 post

.babelrc, src/routes/xp-show.js
Closes  #262 
Supersedes/Closes #263
=> xptracker: Show total xp/ranks only when 'overall' is selected

config-overrides.js, redirect.js, src/components/app.js
=> Use redirect generator for /discord redirect

src/components/app.js, src/components/navigation.js, src/modules/git.js
This was used just for stargazers, but we dont show that anymore.
=> Remove unused git repository fetching

src/components/app.scss, src/components/async.js, src/components/commit.js, src/components/feature.js, src/routes/account/grand-exchange.js, src/routes/account/home.js, src/routes/account/loot-tracker.js, src/routes/gh-auth-code.js, src/routes/home.js, src/routes/loading.js, src/routes/logged-in.js, src/routes/tag-show.js, src/routes/tag.js, src/routes/xp-show.js
- Switch to preact.Fragment instead of using meaningless divs
- Use Bootstrap spacing properties instead of style={}
=> Switch to Fragments from empty divs and utilize Bootstrap

src/index.js, src/modules/account.js, src/modules/bootstrap.js, src/modules/config.js, src/modules/ge.js, src/modules/git.js, src/modules/index.js, src/modules/item.js, src/modules/loot.js, src/modules/xp.js, src/routes/account/grand-exchange.js, src/routes/account/home.js, src/routes/account/loot-tracker.js, src/routes/home.js, src/routes/tag-show.js, src/routes/xp-show.js
=> Switch to bootstrap.json for getting latest release

src/modules/git.js
=> Fix git module action exports

src/routes/account/grand-exchange.js, src/routes/account/home.js, src/routes/account/loot-tracker.js, src/routes/tag-show.js, src/routes/xp-show.js
Before I tried to rely of fetching bootstrap on page load but rendering
is not waiting for it so sometimes it fails to complete in time.
=> Add back fetching of RL version before each RL request

src/_posts/2019-11-14-10-00-1.5.40-Release.md
=> Fix 1.5.40 release post spelling

src/api.js, src/components/hero.js, src/modules/session.js, src/routes/home.js
=> Add logged-in player count to homepage

src/modules/plugin-hub.js, src/routes/plugin-hub.js
=> Sort plugin-hub items by displayName

src/modules/plugin-hub.js, src/routes/plugin-hub.js
=> Add search bar to plugin hub page

src/components/external-plugin.js, src/modules/config.js, src/modules/plugin-hub.js, src/routes/plugin-hub.js
Works only for logged in users
=> Show if external plugin is installed or not on plugin-hub page

src/middleware/thunk-middleware.js, src/modules/config.js, src/modules/item.js, src/routes/account.js, src/routes/account/tags.js, src/routes/tag-show.js, src/routes/tag.css, src/util.js
Add page that displays all tags saved to account
=> Add tags to account/ page

src/modules/item.js
This uses less dumb logic for determining uniqueness of entries
=> Improve performance of item module

src/modules/config.js
=> Strip variation tags in accounts page

src/blog.js
This fixes react-router trying to handle linking to for example images.
=> Fix links to static files in blog posts

src/routes/pulse.js
=> Add count to tooltips for pulse progress bar

src/routes/home.js
It is required for getting latest version for fetching commits
=> Fetch bootstrap on home page

config-overrides.js, package-lock.json, package.json, src/blog.js, src/components/async.js, src/markdown-loader.js
Same markup as images, it just has to end with video extension.
=> Add support for video markup to blog posts

src/modules/loot.js, src/routes/account/loot-tracker.js
This simply assumes that note is always real item id + 1.
Closes #308 
=> Try to get prices for noted items

src/modules/loot.js, src/routes/account/loot-tracker.js
Closes https://github.com/runelite/runelite.net/issues/213
=> Update loot tracker to sort drops by highest value

src/components/tooltip.css, src/routes/account/loot-tracker.js, src/routes/account/tags.js, src/routes/tag.css
=> Make tooltips consistent between all pages

src/routes/account/loot-tracker.js
=> Make spacing in loot tracker consistent with client

src/components/app.scss, src/routes/pulse.js, src/routes/pulse.scss
This style was applid globablly by accident in
92c5fdd8b92d4fe03118c2d087d6808d833d8cf6
=> Apply margin and border only to /pulse list group item

src/modules/plugin-hub.js
=> Lowercase plugin display name when sorting

src/components/search-bar.js, src/routes/plugin-hub.js
=> Added autofocus on search input on plugin hub page

src/modules/plugin-hub.js
=> Replaced fromCharCode string parsing to TextDecoder

src/routes/account.js
=> Show account selector in time tracking panel

src/routes/account/time-tracking.css, src/routes/account/time-tracking.js
=> Add tab navigation to time tracking

src/modules/plugin-hub.js
When using the /plugin-hub search, also search in plugin description and
plugin author.
=> Search also pluginhub author and description

src/components/app.scss, src/components/pagination.js, src/modules/ge.js, src/routes/account/grand-exchange.js, src/util.js
=> Add pagination for grand exchange

src/api.js, src/components/hero.js, src/routes/account.js
=> Remove some unneeded usages of ramda

.github/workflows/CI.yml, README.md
=> Rename GH actions to CI and fix README badge

src/modules/plugin-hub.js, src/routes/plugin-hub.js
=> Add sorting for installed plugins

src/modules/timetracking/BirdHouse.js, src/modules/timetracking/BirdHouseData.js, src/modules/timetracking/BirdHouseSpace.js, src/modules/timetracking/BirdHouseState.js, src/modules/timetracking/BirdHouseTracker.js, src/modules/timetracking/FarmingPatch.js, src/modules/timetracking/FarmingRegion.js, src/modules/timetracking/FarmingTracker.js, src/modules/timetracking/FarmingWorld.js, src/modules/timetracking/PatchImplementation.js, src/modules/timetracking/PatchPrediction.js, src/modules/timetracking/PatchState.js, src/modules/timetracking/Tab.js, src/modules/timetracking/VarPlayer.js, src/modules/timetracking/Varbits.js
The issue in jsweet was resolved, see
https://github.com/cincheo/jsweet/issues/639
=> Regenerate timetracking

src/modules/config.js, src/modules/time-tracking.js, src/modules/timetracking/BirdHouseTracker.js, src/modules/timetracking/FarmingTracker.js, src/modules/timetracking/TimeTrackingConfig.js, src/routes/account.js, src/util.js
=> Add support for new RuneLite profiles

src/modules/timetracking/FarmingTracker.js, src/modules/timetracking/FarmingWorld.js, src/modules/timetracking/PatchImplementation.js, src/modules/timetracking/TimeTrackingConfig.js
=> Integrate farming offset changes from rl master

src/modules/config.js
See runelite/runelite#13143
I'm going to need someone to help me test this.
Edit: I confirmed on my end that it pulls from my rsprofile config fields, but I'd like a second pair of eyes to look the whole thing over.
=> slayer: Modify to use RSProfiles Config

src/_posts/2021-03-24-10-00-1.7.3-Release.md
I opted not to add any images this go around, add some if you feel something here deserves it.
=> Add 1.7.3 post

src/modules/loot.js
=> Add fallback when loot tracker fails to find name for item

redirect.js
=> update discord links to use a link that starts users in #welcome

src/modules/config.js, src/routes/account.js, src/routes/account.scss, src/routes/account/delete.js
Currently PATCH is not allowed by CORS policy so that needs to be fixed first
=> Add support for account/profile deletion

src/components/app.scss, src/routes/account.js, src/routes/account.scss, src/routes/account/delete.js
=> Simplify the message that shows what user data are being deleted

src/routes/account.js, src/routes/account.scss, src/routes/account/delete.js
=> Rename "Accounts" to "RuneScape profiles"

src/routes/account/delete.js
=> Display also account type (league) on profile deletion page

src/components/app.js, src/routes/tile-show.js, src/routes/tile.js
=> Use URL fragment for tile markers to avoid URL limits

src/components/app.scss, src/components/runescape-map.js, src/modules/config.js, src/routes/account.js, src/routes/account/tiles.js, src/routes/tile-show.js
This shows all tile markers (ground markers) for account
=> Add support for account/tile-markers

src/components/app.js, src/components/app.scss, src/components/external-plugin.js, src/components/inner-html-helper.js, src/components/layout.scss, src/index.js, src/modules/plugin-hub.js, src/routes/account.js, src/routes/account.scss, src/routes/blog-show.js, src/routes/home.scss, src/routes/plugin-hub-show.js
- Add pages for plugin-hub plugins that will render the README of the
plugin from repository
- Properly handle scrolling
TODO: Get rid of GIFs/somehow prevent large GIFs from loading? - DONE
Closes #284
Closes #286
=> Add plugin hub plugin pages (/plugin-hub/show/<internalName>)

src/components/external-plugin.js, src/modules/plugin-hub.js
=> Strip HTML from plugin description in plugin hub pages

src/modules/plugin-hub.js
=> Fix all relative links to plugin hub assets

src/modules/plugin-hub.js
=> Fix .gif replacing when there are multiple img tags in a row

src/routes/plugin-hub-show.js
=> Return 404 if external plugin was not found

src/components/runescape-map.js
This will lock/unlock current view so you can free scroll.
=> Add lock/unlock button to RuneScape map

src/components/runescape-map.js, src/components/runescape-map.scss
=> Switch from Explv to mejrs.github.io as map source

src/components/runescape-map.js
=> Add plane change buttons

src/routes/tag-show.js, src/routes/tile-show.js
=> Return NotFound page for missing and invalid tags and markers

public/index.html, src/components/meta.js, src/markdown-loader.js, src/routes/blog-show.js, src/util.js
With these meta tags discord/facebook/twitter embeds should show
additional data (like proper preview image etc).
=> Add additional meta tags for social media

src/index.js
=> Fix hash navigation

src/routes/home.js, src/routes/home.scss
Not sure for how long is this broken I just randomly noticed it
=> Fix Show all features button on homepage

package-lock.json, package.json, src/_data/hero.js, src/components/hero.js, src/components/hero.scss
- Detect aarch64 for Linux
- Get rid of platform.js as navigator.platform is built in and better
(kind of)
- Add support for multiple download buttons if there are multiple
entries for same os
- Show OS icon on main download buttons
=> Update platform detection code

src/routes/gh-auth-code.js
=> Update gh-auth-code with /ghauth command

src/components/hero.js
=> Prevent bots from crawling download links

src/util.js
Fixes #446 
PBs are now rounded to one decimal place
=> Update toMMSS helper function to handle rounding of decimals

src/modules/config.js, src/routes/account.js, src/routes/account/loot-tracker.js
=> Add sanity checks to loot config

src/components/external-plugin.js, src/components/feature.scss, src/routes/plugin-hub-show.js
This makes headers a bit nicer and larger when looking at specific
plugin hub plugin.
=> Improve plugin-hub plugin display

src/modules/account.js, src/routes/logged-in.js
=> Switch to new oauth API

.github/workflows/CI.yml, package-lock.json, package.json
This introduces a bunch of warnings from bootstrap, which you can update if you want them to go away.
=> use dart sass for node 16 compat

src/modules/config.js
=> Properly send edit as map instead of list when updating config

src/components/external-plugin.js, src/components/tooltip.css, src/modules/plugin-hub.js
=> Switch to new plugin hub format

src/modules/plugin-hub.js
This primarily fixes handling of relative links. Previously it would always use raw.githubusercontent.com for all urls, now use use github.com for anchors, and r.g.c for images, which more closely matches GitHub's logic.
=> use DOMParser for parsing readme HTML

src/components/footer.js
Sorry for the annoying PRs.
Should be all good now
=> Fix footer RSS link

src/routes/plugin-hub-show.js
Fixed issue when externalPlugin.github is null.
Fixes https://github.com/runelite/runelite.net/issues/496
=> Fix plugin hub show

src/_posts/2018-05-25-23-00-Phishing-Attempts.md
The first thing which pops up when googling my name is "Phishing attempts" lol
=> Scrub name from post

public/index.html
I'm not really sure why we never had this before tbh
=> Add RSS feed link
