- src/_data/features.js
The features page seemed to be missing clear writing style conventions. This should help establish a strong example for future additions.
Titles
- Standardised to sentence case except for place names
Descriptions
- Enforced simple present tense for all sentences
- Removed some repeated openers like "Allows you to..." and "Displays various information..."
- Replaced "amount of" with "number of" for countable nouns
- Separated a few words that aren't conjoined in-game (rune pouch, team cape)
- Increased the clarity of a few feature summaries
> Improve consistency of the language text in data/features.js

- src/containers/xp/show.js
Remove the curve from the following line graphs:
* Skill rank
* Experience gained
Before(Curve):
After(Straight):
Fixes #56
> Xptracker: remove curve from the line graphs

- public/index.html
- src/components/hero.js
- src/redux/modules/runelite.js
We do have a couple of users that try to use the site on IE11 and they end up downloading the all platforms jar and opening it in notepad. This makes the site's render work as it does on other browsers, on IE11. The `Object.values` patch is included because without it, opening the devtools crashes IE.
Fixes #75
> Support for Internet Explorer 11

- config-overrides.js
- package-lock.json
- package.json
- src/blog.js
- src/components/app.js
- src/components/hero.js
- src/containers/blog-show.js
- src/containers/blog.js
- src/containers/home.js
- Replace react with preact as preact is smaller and faster alternative to
react and this opens possibilities to use preact-specific minimal
libraries later.
- Add create-react-app-rewired to add support for preact aliasing
> Switch from react to preact

- config-overrides.js
- package-lock.json
- package.json
Replace big and slow react-snap pre-renderer with smaller webpack
prerender plugin.
> Replace react-snap with smaller webpack prerender

- package-lock.json
- package.json
- src/modules/runelite.js
- src/routes/xp-show.js
- Instead of using huge moment.js use day.js what is mostly max ~2kb in size (compared to almost 20kb of moment.js)
- The total bundle size is mostly not changed, the moment.js dependency was moved to xp-tracker chunk because chart.js is already using moment. This will reduce the overhead everywhere else except XP tracker page
- Make chart.js continuously update its data instead of fully recreating entire chart every property change
> Replace moment.js with day.js, make chart.js continuosly update

- config-overrides.js
- package-lock.json
- package.json
- src/modules/app.js
- src/modules/git.js
- src/modules/navigation.js
- src/modules/runelite.js
- src/routes/home.js
- src/routes/xp-show.js
- Switch from redux-routine to simply dispatching end actions
- Use createActions instead of createAction per-action and use .toString
on actions to handle them in reducers
- Fix prerendering being run in dev mode
> Simplify redux modules

- src/routes/home.js
Do not remove the URL part from feature data object when building the
feature components on home page.
> Fix links for homepage features

- src/components/app.css
- src/components/app.js
- src/components/navigation.js
- src/components/tooltip.css
- src/modules/index.js
- src/modules/runelite.js
- src/modules/tag.js
- src/routes/tag-show.css
- src/routes/tag-show.js
- src/routes/tag.css
- src/routes/tag.js
This adds ability to view clipboard output of https://github.com/runelite/runelite/pull/6024
Example:
```
http://localhost:3000/tag/show/raids,19481,8842,3024,22109,12899,11771,19553,19547,12018,12006,12002,13441,12695,6739,5952,21795,12625,12612,11889,6570,12954,12926,11804,12797,12791,19933,13073,13072,19484,19481,11665,11664,11663,13393,2444,6685
```
+ added endpoint for `/tag` so you can enter tag there
Preview:
> Add /tag/show/:csv for showing tag tab

- src/_data/links.js
- src/components/navigation.js
In order to reduce navigation bar bloat, move all social icons (Discord,
Twitter, GitHub) on right and remove their descriptions (leave just
icons).
Preview:
> Move social icons at right and remove descriptions

- src/components/app.scss
- src/routes/blog-show.css
- src/routes/blog-show.js
In addition to applying max-width: 100% for responsive images in blog
posts, apply this rule to home page blog post too.
> Apply markdown-body max img width also on home

- src/components/app.scss
- src/components/hero.js
This removes weird gradient that is happening only on webkit-based
browsers.
> Remove type=button from website button links

- src/routes/blog-show.js
To workaround bug in Preact
https://github.com/developit/preact/issues/844 move setting of
dangerouslySetInnerHTML property to helper component. This bug most
likely surfaced because I moved logic to build blog post to separate
function instead of making anonumous function every time.
> Extract dangerouslySetInnerHtml to separate component

- package-lock.json
- package.json
To resolve XSS security vulnerability listed here:
https://nvd.nist.gov/vuln/detail/CVE-2019-8331.
We don't use tooltips and tooltip-data properties from Bootstrap JS, but
its still better to just update.
> Bump Bootstrap to 4.3.1

- src/routes/account/home.js
As kill count is always present but PB might be not (because very often
bosses dont have it) just put it on left so kc are always at same place.
> Put personal best before kill count

- src/routes/account/loot-tracker.js
- src/routes/tag-show.js
- src/util.js
this still isn't 100% correct because of the lack of a noted > unnoted mapping, but I don't think this will cause any actual errors.
> more correctly use RSLookup

- config-overrides.js
Rendering some routes concurrently can make prerenderer fail. This will
slightly increase build time but at least it will be stable.
> Limit concurrent routes in prerenderer

- src/modules/loot.js
ramda's uniq uses a O(N) set with a slow equals method, so just don't save loot between page loads
> Speed up loot tracker

- src/routes/blog-show.js
This adds a title in the form "Fri May 03 2019 10:00:00 GMT+0000 (Coordinated Universal Time)" to the post date. (that is, the default String cast of the Date object)
Closes #233
> blog post: Add precise date as title attribute on date

- src/routes/account.js
If you have loot tracker with a decent amount of loot, the Export feature doesnt work as the data becomes too big to download with a URI.
Example:
> Fix: JSON exports reach maximum length and download fails

- src/components/hero.css
- src/routes/account/loot-tracker.js
- src/util.js
Some browsers on mobile devices do not really support
background-attachment fixed because of performance reasons, so simply
disable it. Also add some other compatiblity stuff just in case.
Related stackoverflow post:
https://stackoverflow.com/questions/20443574/fixed-background-image-with-ios7
> Fix homepage header display on mobile devices

- redirect.js
- src/_data/links.js
- src/components/navigation.js
- Switch from links.discord to /discord redirect in navbar
- Remove links.discord
> Use /discord link for Discord invites in navbar

- config-overrides.js
Because apparently minify means break.
> Disable minification of atom.xml

- src/components/navigation.js
Whilst on the RuneLite homepage, clicking the Discord button in the navigation pane doesn't work. From what I can tell, some JavaScript in React is hijacking the click function. With all JS disabled, the button works as expected. I noticed that setting the link to the Discord redirect page as an absolute link fixes this problem, although there is likely a better way of fixing this issue. Unfortunately I don't know React, which may have it's own conventions to fix this, but this is good enough IMO.
> Fix the Discord link in the navigation pane.

- src/modules/loot.js
Adding ability to search loot tracker by item name
> Ability to search loot tracker by item name

- src/modules/config.js
- src/routes/account.js
Turns out bank tags are actually not account-based.
> Load tags without account-based config prefix

- src/components/app.scss
This was previously set only for blog posts in blog/show, so for
consistency use same color everywhere.
> Make all links orange

- src/components/app.js
- src/components/app.scss
- src/components/commit.js
- src/components/navigation.js
- src/middleware/thunk-middleware.js
- src/modules/git.js
- src/routes/blog.scss
- src/routes/pulse.js
- src/store.js
Pulse page shows list of merged and opened pull requests and new commits
since last release.
In my opinion this is very nice page to have for people to see what is coming in next release and also for developers writing blog posts. I am not sure what else it can show so suggestions are welcome.
> Add /pulse page

- src/components/layout.scss
- src/components/tooltip.css
Change overflow of content-display to visible to allow tooltips to show
outside of it.
> Fix tooltip display when out of parent div

- src/markdown-loader.js
Thanks to new markdown processor this can be simply injected into
renderer instead of using regex replace.
> Optimize adding of `native` tag to blog links

- src/routes/plugin-hub.js
Left it there by accident when adding interpolated author field to
title.
Oops
> Remove extra dollar symbol from plugin-hub title

- src/routes/account/tags.js
- src/routes/tag-show.js
Instead of tags being centered on /tag/show and /account/tags, align
them left.
> Align tags left instead of center

- src/modules/loot.js
Makes the website's loot tracker more consistent with the one in the client by stacking the clue scroll drops together.
> loot: make same tier clue scrolls stack

- src/modules/config.js
As usernames are case insensitive (and rest of the configs are as well on the site), lowercase all config keys when fetching
configuration.
Closes #362
> Lowercase config keys

- src/modules/config.js
- src/modules/plugin-hub.js
Lowercasing all config keys broke matching for slayer task and installed
external plugins, so normalize all keys checked against config as well.
> Fix config key matching

- src/routes/account/home.js
Icons added for: 
- Sarachnis
- Herbiboar
- Zalcano
- Gauntlet
- Corrupted Gauntlet
- Mimic
- Ape Atoll Agility
> Add varius missing boss log icons

- src/components/app.scss
- src/components/choice.js
- src/components/external-plugin.js
- src/modules/plugin-hub.js
- src/routes/plugin-hub.js
- Add user counter next to each plugin
- Add support for sorting by name or user count
> Add support for plugin hub user count

- src/modules/plugin-hub.js
> Temporarily switch to 1.6.30-SNAPSHOT for plugin hub stats

- src/modules/plugin-hub.js
- src/routes/plugin-hub.js
Currently this is using temporary testing URL provided by abex. The url needs to be changed back before merging this.
> Add plugin hub sorting based on updated and created time

- src/components/tooltip.css
- src/routes/account.scss
This fixes https://github.com/runelite/runelite.net/issues/341
I'm not sure if this is a bug with safari but it looks like the culprit is `column-count` on `card-columns`. I'm also not sure if the safari engine caches styles when using `column-count` for performance reasons but it looks like if you enable gpu acceleration on the cards it'll solve this issue.
> Fix safari hover bug

- src/modules/ge.js
As of commit 06b8e1b79881d6d6e171905d64c5f2891e2335cc, RuneLite encodes
`Instant`s as epoch millis. This commit updates references to fields of
that type to be read correctly.
> Fix Instant parsing

- src/components/runescape-map.js
- src/components/runescape-map.scss
- src/routes/tile-show.js
- Use map center for determining region name for tile markers instead of
relying on provided tiles
- Move region label to map instead of it being header above map
- Improve map button style to match rest of the site
> Use map center for determining region name for tile markers & improve button/region headers

- src/components/app.scss
- src/routes/account/tags.js
- src/routes/account/tiles.js
These buttons will navigate users to /tag/show and /tile/show with
selected data that is ready to be shared with others.
> Add Share buttons to /account/tags and /account/tile-markers

- config-overrides.js
- src/components/loading.js
- src/components/prepare.js
- src/components/runescape-map.js
Instead of showing target page directly, loading component will be shown
while data are being loaded. This also prevents displaying 404 page on
first load of plugin pages etc.
> Add Loading component that is shown when data are loaded

- src/components/runescape-map.js
Now they should stay disabled properly when at max/min layers
> Fix layer change buttons disabling

- src/markdown-loader.js
This stop google from attempting to crawl those links and then try to
crawl for example account page or pulse page.
> Add nofollow to blog links

- src/routes/gh-auth-code.js
If a user copies the full command with token, Discord won't recognise it
as a slash command, causing the message to get posted to the channel.
This is not good. Turns out that to have it recognised with the token,
the arg name needs to be provided. Adding `oauth_code:` to the command
to copy results in Discord correctly identifying it as a slash command,
and it's filled out correctly.
> Update /ghauth message to include `oauth_code:`

- src/routes/plugin-hub-show.js
- src/routes/plugin-hub.js
| Before | After |
|:----------:|:-------:|
| ![Screenshot 2023-07-16 at 23-09-51 CoX Timers   Additions - Plugin Hub - RuneLite](https://github.com/runelite/runelite.net/assets/2199511/2f28b17e-90e3-4b7d-ab91-7d05295e71f6) | ![Screenshot 2023-07-16 at 23-10-10 CoX Timers   Additions - Plugin Hub - RuneLite](https://github.com/runelite/runelite.net/assets/2199511/6fce766f-0455-48f7-a6fa-24063ebb440a) |
> Remove extra space between plugin hub sections and footer
